AdsWeb/Controllers/FreeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Common;
using AdsEntity;
using AdsEntity.WechatEntity;
using AdsWeb.WechatServices;
using AdsDal;
using PagedList;
using PagedList.Mvc;
using AdsServices;
using AdsWeb.AliyunVideo;
using System.Globalization;
using PsyCoderWechat.WechatPay;
namespace AdsWeb.Controllers
{
    [AllowAnonymous]
    public class FreeController : Controller
    {
        private UnitOfWork unitOfWork = new UnitOfWork();
        public ActionResult FreeScale()
        {
           
           return View();
              
        }
       
        #region 量表报告详情页面
        public ActionResult FreeBaogaoDetail(string score, string Dementionscore, string totalscore, string weight)
        {



            string[] sArray = Dementionscore.Split(',');
            List<BaogaoDemention> demlist = new List<BaogaoDemention>();
            string chartscategories = "[";
            string chartsdata = "[";

            foreach (string s in sArray)
            {
                // string  dem=s.ToString();
                BaogaoDemention dem = new BaogaoDemention();
                dem.demName = s.Substring(0, s.IndexOf(":"));
                dem.demScore = int.Parse(s.Substring(s.IndexOf(":") + 1));
                if (dem.demName == "感觉能力")
                {
                    dem.demReference = 30;
                }
                if (dem.demName == "交往能力")
                {
                    dem.demReference = 44;
                }
                if (dem.demName == "运动能力")
                {
                    dem.demReference = 29;
                }
                if (dem.demName == "语言能力")
                {
                    dem.demReference = 31;
                }
                if (dem.demName == "自理能力")
                {
                    dem.demReference = 25;
                }


                demlist.Add(dem);
                chartscategories = chartscategories + "\"" + dem.demName + "\"" + ",";
                chartsdata = chartsdata + dem.demScore + ",";
            }
            chartscategories = chartscategories.TrimEnd(',') + "]";
            chartsdata = chartsdata.TrimEnd(',') + "]";
            ViewData["dem"] = demlist;
            ViewBag.total = totalscore;
            ViewBag.categories = chartscategories;
            ViewBag.chartsdata = chartsdata;

            return View();
        }


        #endregion


        #region 2心理服务
        public ActionResult FreeHeartList(int? page)
        {


            string sqlpara = CategoryServices.GetChildIdLisForSql(4);

            Pager pager = new Pager();
            pager.table = "AdsVideo";
            pager.strwhere = "VideoCategory in" + sqlpara;
            pager.PageSize = 50;
            pager.PageNo = page ?? 1;
            pager.FieldKey = "VideoId";
            pager.FiledOrder = "VideoId desc";

            pager = CommonDal.GetPager(pager);
            IList<AdsVideo> videos = DataConvertHelper<AdsVideo>.ConvertToModel(pager.EntityDataTable);
            var videosAsIPageList = new StaticPagedList<AdsVideo>(videos, pager.PageNo, pager.PageSize, pager.Amount);


            return View(videosAsIPageList);



        }
        #endregion

        public ActionResult SaleBabys(int? page, int id)
        {
            Pager pager = new Pager();
            pager.table = "AdsBaby";
            pager.strwhere = "SalerCode=" + id;
            pager.PageSize = 20;
            pager.PageNo = page ?? 1;
            pager.FieldKey = "BabyId";
            pager.FiledOrder = "BabyId desc";

            pager = CommonDal.GetPager(pager);
            IList<AdsBaby> babys = DataConvertHelper<AdsBaby>.ConvertToModel(pager.EntityDataTable);
            var babysAsIPageList = new StaticPagedList<AdsBaby>(babys, pager.PageNo, pager.PageSize, pager.Amount);
            ViewBag.salercode = id;
            return View(babysAsIPageList);
        }

        public ActionResult GetImg(int id,string oldpath,int? xx,int ?yy)
        {
            oldpath = @"/Resource/img/"+oldpath;
            string filename = System.DateTime.Now.ToUniversalTime().Ticks.ToString() + CommonTools.getRandomNumber(1000, 9999).ToString()+"_" + id.ToString() + ".jpg";
            string newpath = @"/Resource/img/"+filename;
            
            int x =xx?? 285;
            int y =yy?? 870;
            string textimg = ImageTools.composeTextPoint(oldpath, id.ToString(), newpath, x, y);
            ViewBag.img = newpath;
            ViewBag.salercode = id;
            return View();
        }

        //项目相关的页面
        public ActionResult FreeHeartServices(int id)
        {
            string ApiUrl = AliyunCommonParaConfig.ApiUrl;
            // 注意这里需要使用UTC时间，比北京时间少8小时。
            string Timestamp = DateTime.Now.ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ", DateTimeFormatInfo.InvariantInfo);
            string Action = "GetVideoPlayAuth";
            string SignatureNonce = CommonTools.EncryptToSHA1(CommonTools.GenerateRandomNumber(8));


            AdsVideo video = unitOfWork.adsVideosRepository.GetByID(id);
            string VideoId = video.VideoUrl;
            ViewBag.VideoId = VideoId;

            ViewBag.PlayAuth = AliyunVideoServices.GetVideoInfo(ApiUrl, VideoId, Timestamp, Action, SignatureNonce).PlayAuth;

            return View(video);
        }

    }
}

AdsWeb/Views/Free/FreeBaogaoDetail.cshtml
@using AdsEntity;
@{
    Layout = "~/Views/Shared/_FreeLayout.cshtml";
}


<div class="row skyindexrow">
    <div class=" text-orange skyindexrowtitle"><i class="glyphicon glyphicon-heart"></i> 自闭症行为量表的测评报告</div>
</div>

<div style="background-color:#ffffff">
    <table class="table table-bordered">
        <thead>
            <tr>

                <th>统计项目</th>
                <th>项目总分</th>
                <th>项目得分</th>
            </tr>

            @foreach (BaogaoDemention dem in ViewData["dem"] as List<BaogaoDemention>)
            {

               
                
                 <tr>

                 <td>@dem.demName</td>
               
                 <td>@dem.demReference</td>
                 <td>@dem.demScore</td>
            </tr>
                
                
            }
          
            <tr>
                <td>总分</td>
               
                <td>参考值：筛查界限57分/诊断界限67分</td>
                <td>@ViewBag.total</td>
            </tr>
        </thead>
        <tbody>

            <tr>

                <th colspan="4">量表详情</th>


            </tr>
            <tr>

                <td colspan="4">
                <div id="main" style="width: 100%;height:400px;"></div>
                </td>


            </tr>
            <tr>

                <th colspan="4">结果分析</th>


            </tr>
            <tr>

                
                   @if (int.Parse(ViewBag.total) >= 67)
{
    <td colspan="4">
        您的总得分是：@ViewBag.total 分.<br />
        根据量表筛查界限分为57分，诊断分数为67分。<br />
        您的分数超过了诊断分数，建议您继续进行康复训练
    </td>
}
                   @if (int.Parse(ViewBag.total) < 57)
                       {
    <td colspan="4">
        您的总得分是：@ViewBag.total 分.<br />
        根据量表筛查界限分为57分，诊断分数为67分。<br />
        根据您的测量结果，你未达到筛查分数，如有疑问建议到专业机构进行咨询。
    </td>
}
                 
                   @if (int.Parse(ViewBag.total) >= 57 && int.Parse(ViewBag.total) < 67)
                  
                   {
    <td colspan="4">
        您的总得分是：@ViewBag.total 分.<br />
        根据量表筛查界限分为57分，诊断分数为67分。<br />
        根据您的测量结果，你达到了筛查分数，建议您立刻到专业机构进行诊断，并马上开始进行康复训练。<br />
    </td>
}
                 
                   
        


            </tr>
            <tr>
                <th colspan="4">【客服咨询】</th>
            </tr>
            <tr>
                <td colspan="4">
                    客服电话：13945016428<br />
                </td>
            </tr>
            <tr>
                <td colspan="4">说明：<br />心理测量仅仅是对自闭症儿童的初步评测，测评结果仅供参考。<br/>
                    <br /><br /><br /><br />
                </td>
</tr>

        </tbody>

    </table>
    


</div>



@section FootScripts {
   <script type="text/javascript" src="/plugins/echarts.min.js"></script>

<script type="text/javascript">
    // 基于准备好的dom，初始化echarts实例
    var myChart = echarts.init(document.getElementById('main'));

    // 指定图表的配置项和数据
    var option = {
        title: {
           // text: '自闭症行为量表分析'
        },
        tooltip: {},
        legend: {
            data: ['自闭症行为']
        },
        xAxis: {
            data: ["感觉", "交往", "运动", "语言", "自理"]
        },
        yAxis: {},
        series: [{
            itemStyle: {
                normal: {
                    //好，这里就是重头戏了，定义一个list，然后根据所以取得不同的值，这样就实现了，
                    color: function (params) {
                        // build a color map as your need.
                        var colorList = [
                          '#C1232B',  '#E87C25', '#27727B',
                           '#FE8463',  '#26C0C0'
                        ];
                        return colorList[params.dataIndex]
                    },
                    //以下为是否显示，显示位置和显示格式的设置了
                    label: {
                        show: true,
                        position: 'top',
                        //                             formatter: '{c}'
                        formatter: '{b}\n{c}'
                    }
                }
            },
            type: 'bar',
            data: @ViewBag.chartsdata ,
        }]
    };

    // 使用刚指定的配置项和数据显示图表。
    myChart.setOption(option);
</script>

    }

AdsWeb/Views/Free/FreeHeartList.cshtml
@model StaticPagedList<AdsEntity.AdsVideo>
@using PagedList;
@using PagedList.Mvc;
@using AdsServices;
@{
    Layout = "~/Views/Shared/_FreeLayout.cshtml";
}


        <div class="row">
            <img src="~/WechatResource/img/heart.jpg" alt="User Avatar" style="width:100%;height:180px;">
        </div>

        <div class="row skyindexrow">
            <div class="pull-left text-orange skyindexrowtitle"><i class="glyphicon glyphicon-heart"></i> 心理服务</div>
    
        </div>


@foreach (var item in Model)
{
     <div class="row skyindexrow">

         <img src="@item.VideoPhoto" alt="User Avatar" class="pull-left sky-index-itemimg">
            <div class="pull-left sky-index-itemcontent">
                <span class="sky-index-itemcontent-title">
                   @Html.DisplayFor(modelItem => item.VideoName)
                </span>
                <p>讲师：@Html.DisplayFor(modelItem => item.VideoTeacher)</p>
                <p><i class="glyphicon glyphicon-eye-open"></i> 1000+</p>
            </div>

         <a class="pull-right btn btn-warning btn-sm" href="@Url.Action("FreeHeartServices", "Free", new { id = item.VideoId })">马上学习</a>

        </div>

}

<div class="box-footer clearfix">
    <ul>
        @Html.PagedListPager((IPagedList)Model, page => Url.Action("Ceping", new { page = page }),
    new PagedListRenderOptions
    {
        LinkToPreviousPageFormat = "上一页",
        LinkToNextPageFormat = "下一页",
        DisplayLinkToFirstPage = PagedListDisplayMode.Always,
        DisplayLinkToLastPage = PagedListDisplayMode.Always,
        DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
        DisplayLinkToNextPage = PagedListDisplayMode.Always,
        MaximumPageNumbersToDisplay = 5,
        LinkToFirstPageFormat = "首页",
        LinkToLastPageFormat = "最后一页",
        PageCountAndCurrentLocationFormat = "第 {0}页 共 {1}页"
    })
    </ul>
</div>


       

AdsWeb/Views/Free/FreeHeartServices.cshtml
@model AdsEntity.AdsVideo
@{
    Layout = "~/Views/Shared/_FreeLayout.cshtml";
}

@section Topcss {
<link rel="stylesheet" href="https://g.alicdn.com/de/prismplayer/1.7.6/skins/default/index.css" />
}

<div class="row" style="background-color: #ffffff; ">
    <div class="col-xs-12 prism-player" style="height: 150px;" id="J_prismPlayer">
    </div> 
      
   
    <div class="row" style="background-color:#666666;margin: 0px 0px 0px 10px;">
        <div class="col-xs-12" style="background-color:#ffffff; border-top: solid #efefef 1px;">
            <div>
                <h3 class="sky-x-2">@Model.VideoName</h3>

                <!--<span class="description-text">34万星宝正在使用</span>-->
                <span></span>
            </div>

            <!-- /.description-block -->
        </div>
        <!-- /.col -->
        <!-- /.col -->
    </div>

</div>





<table class="table" style="background-color:#ffffff">
    <tbody>


        <tr>
            <th colspan="4">【项目介绍】</th>
        </tr>
        <tr>
            <td colspan="4">
                @Html.Raw(Model.VideoInfo)
            </td>
        </tr>
      

        <tr>
            <th colspan="4">【一对一咨询】</th>
        </tr>
        <tr>
            <td colspan="4">
                客服电话：13945016428<br />
            </td>
        </tr>


    </tbody>

</table>

@section FootScripts {


<script type="text/javascript" src="https://g.alicdn.com/de/prismplayer/1.7.6/prism.js"></script>
    <script type="text/javascript">

        //初始化编辑器
    var player = new prismplayer({
        id: "J_prismPlayer",
        autoplay: false,
        width: "100%", height: "300px",
        vid: "@ViewBag.VideoId",
        playauth: "@ViewBag.PlayAuth",
    });


        function pingjia(babyId, pingjiaValue, videoId) {
            $.ajax({
                type: 'POST',
                url: "/Wechat/PingjiaCreate",
                data: {
                    pingjiaValue: pingjiaValue,
                    babyId: babyId,
                    videoId: videoId,
                },
                dataType: "json",
                success: function (data) {
                    if (data.MessageStatus)
                    { alert(data.MessageInfo); }
                    else
                    { alert("评价失败"); }

                }
            });

        }


       
</script>
}

AdsWeb/Views/Free/FreeScale.cshtml
@model AdsEntity.AdsBaby
@{
    Layout = "~/Views/Shared/_FreeLayout.cshtml";
}


   
<div id="adsabc">

</div>

@section FootScripts {
<script src="~/WechatResource/js/labelauty.js"></script>
<script src="~/WechatResource/js/ADSABC.js"></script>
    }

AdsWeb/Views/Free/GetImg.cshtml
@model StaticPagedList<AdsEntity.AdsBaby>
@using PagedList;
@using PagedList.Mvc;
@using AdsServices;
@{
    Layout = "~/Views/Shared/_FreeLayout.cshtml";
}
        <div class="row skyindexrow">
            <div class="pull-left text-orange skyindexrowtitle">您的编号为: @ViewBag.salercode 您的姓名： @SalerServices.GetSalerName(ViewBag.salercode) </div>  
        </div>


<table class="table table-bordered table-hover">
    <thead>
        <tr>
           
            <th class="col-sm-2">
                客户名称
            </th>
            <th class="col-sm-2">
                星童名称
            </th>

            <th class="col-sm-2">
                到期时间
            </th>
            <th class="col-sm-3">状态</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
               
                <td>
                    @CustomerServices.GetCustomerName(item.CustomerId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BabyName)
                </td>
                <td>
                    @item.BabyExpiredTime.GetValueOrDefault().ToString("yyyy-MM-dd")
                </td>

                <td>
                    <button class="btn btn-xs btn-@(item.Babystatus?"success":"danger")">@(item.Babystatus ? "已付费" : "未付费")</button>
                </td>


            </tr>

        }

    </tbody>
</table>



<div class="box-footer clearfix">
    <ul>
        @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page = page }),
    new PagedListRenderOptions
    {
        LinkToPreviousPageFormat = "上一页",
        LinkToNextPageFormat = "下一页",
        DisplayLinkToFirstPage = PagedListDisplayMode.Always,
        DisplayLinkToLastPage = PagedListDisplayMode.Always,
        DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
        DisplayLinkToNextPage = PagedListDisplayMode.Always,
        MaximumPageNumbersToDisplay = 5,
        LinkToFirstPageFormat = "首页",
        LinkToLastPageFormat = "最后一页",
        PageCountAndCurrentLocationFormat = "第 {0}页 共 {1}页"
    })
    </ul>
</div>


       

AdsWeb/Views/Free/SaleBabys.cshtml
@model StaticPagedList<AdsEntity.AdsBaby>
@using PagedList;
@using PagedList.Mvc;
@using AdsServices;
@{
    Layout = "~/Views/Shared/_FreeLayout.cshtml";
}
        <div class="row skyindexrow">
            <div class="pull-left text-orange skyindexrowtitle">您的编号为: @ViewBag.salercode 您的姓名： @SalerServices.GetSalerName(ViewBag.salercode) </div>  
        </div>


<table class="table table-bordered table-hover">
    <thead>
        <tr>
           
            <th class="col-sm-2">
                客户名称
            </th>
            <th class="col-sm-2">
                星童名称
            </th>

            <th class="col-sm-2">
                到期时间
            </th>
            <th class="col-sm-3">状态</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
               
                <td>
                    @CustomerServices.GetCustomerName(item.CustomerId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BabyName)
                </td>
                <td>
                    @item.BabyExpiredTime.GetValueOrDefault().ToString("yyyy-MM-dd")
                </td>

                <td>
                    <button class="btn btn-xs btn-@(item.Babystatus?"success":"danger")">@(item.Babystatus ? "已付费" : "未付费")</button>
                </td>


            </tr>

        }

    </tbody>
</table>



<div class="box-footer clearfix">
    <ul>
        @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page = page }),
    new PagedListRenderOptions
    {
        LinkToPreviousPageFormat = "上一页",
        LinkToNextPageFormat = "下一页",
        DisplayLinkToFirstPage = PagedListDisplayMode.Always,
        DisplayLinkToLastPage = PagedListDisplayMode.Always,
        DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
        DisplayLinkToNextPage = PagedListDisplayMode.Always,
        MaximumPageNumbersToDisplay = 5,
        LinkToFirstPageFormat = "首页",
        LinkToLastPageFormat = "最后一页",
        PageCountAndCurrentLocationFormat = "第 {0}页 共 {1}页"
    })
    </ul>
</div>


       