AdsWeb/Controllers/WechatMessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdsEntity.WechatEntity;
using Common;
using Newtonsoft.Json;
using AdsWeb.WechatServices;

namespace AdsWeb.Controllers
{
    public class WechatMessageController : Controller
    {
        //
        // GET: /WechatMessage/
        public ActionResult TempletMessage()
        {
            return View();

        }
       
        public ActionResult SendTempletMessage()
        {
            WechatTemplateMessage msgData = new WechatTemplateMessage
            {
                touser = "on5dLwiMZ_E06gwpY2pq3Bj4glZ8",
                template_id = "S0jkUpR2R7C6PIpnJHRD1GxIad27dln4vEOtD7uRl4A",
                url = "http://www.baidu.com",
                data = new
                {

                    first = new
                    {
                        value = "宝贝，你好，训练时间到了",
                        color = "#173177"
                    },
                    keyword1 = new
                    {
                        value = "踢皮球运动",
                        color = "#173177"
                    },
                    keyword2 = new
                    {
                        value = "30分钟",
                        color = "#173177"
                    },
                    remark = new
                    {
                        value = "感谢您的参与。"
                    }
                }
            };

            string access_token = AccessTokenService.GetAccessToken();
            string postdata = JsonConvert.SerializeObject(msgData);

            string result = WechatMessageServices.SendTempletMessge(access_token, postdata);

            WechatResult wechatResult = JsonConvert.DeserializeObject<WechatResult>(result);
            if (wechatResult.errcode == 0)
            {
                ViewBag.msg = "模板消息发送成功！操作代码如下：";
                ViewBag.result = result;
            }
            else
            {
                ViewBag.msg = "模板消息发送失败！错误代码如下：";
                ViewBag.result = result;

            }

            return View();
        }
	}
}

AdsWeb/Views/WechatMessage/SendImageMessage.cshtml
 <!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        微信消息发送管理
        
    </h1>
</section>
<!-- Main content -->
<section class="content">
    <div class="well text-center">
        <h3 class="text-red">@ViewBag.msg</h3>
        @ViewBag.result
    </div>
</section>
<!-- /.content -->

AdsWeb/Views/WechatMessage/SendTempletMessage.cshtml
 <!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        微信消息发送管理
        
    </h1>
</section>
<!-- Main content -->
<section class="content">
    <div class="well text-center">
        <h3 class="text-red">@ViewBag.msg</h3>
        @ViewBag.result
    </div>
</section>
<!-- /.content -->

AdsWeb/Views/WechatMessage/TempletMessage.cshtml
 <!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        微信消息发送管理
        
    </h1>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">模板消息管理</h3>
                    <div class="box-tools">
                        <div class="input-group input-group-sm" style="width: 150px;">
                            <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">
                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <tr>
                            <th>ID</th>
                            <th>模板ID</th>
                            <th>模板标题</th>
                            <th>模板内容</th>
                            <th>发送测试账号</th>
                            <th>测试发送</th>
                        </tr>
                        <tr>
                            <td>1</td>
                            <td>S0jkUpR2R7C6PIpnJHRD1GxIad27dln4vEOtD7uRl4A</td>
                            <td>课程提醒</td>
                            <td>欢迎词：{{welcome.DATA}} 第一个参数：{{first.DATA}} 第二个参数：{{second.DATA}} </td>
                            <td>on5dLwiMZ_E06gwpY2pq3Bj4glZ8</td>                         
                            <td><a class="btn btn-info btn-sm" href="@Url.Action("SendTempletMessage", "WechatMessage")">发送测试</a> </td>
                        </tr>

                       
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>
</section>
<!-- /.content -->